version: '3.8'
services:
  web:
    build:
      context: app
      target: builder
    logging:
      driver: json-file
    ports: 
      - '80:80'
    volumes:
      - ./app:/var/www/html/
    deploy:
      replicas: 1
      resources:
        reservation:
          cpus: '0.1'
          memory: 10m
        limits:
          cpus: '0.4'
          memory: 64m
