version: '3.3'
services:
  server:
    image: php:8.0.9-apache
    command: 
      - /bin/sh 
      - -c 
      - |
        apt-get update
        apt-get install -y --no-install-recommends git
        apt-get install wget
        File=index.php
        if [ -f "$File" ]; then
        echo ""
        else
        wget https://raw.githubusercontent.com/thanawat1303/swarm01/main/app/index.php
        fi
        apache2-foreground
    networks:
     - webproxy
    logging:
      driver: json-file
      options:
        "max-size": "10m"
        "max-file": "5"
    volumes:
      - app:/var/www/html/
    container_name: apache2
    deploy:
      replicas: 1
      labels:
        - traefik.docker.network=webproxy
        - traefik.enable=true
        - traefik.http.routers.spcn19apache-https.entrypoints=websecure
        - traefik.http.routers.spcn19apache-https.rule=Host("spcn19apache.xops.ipv9.xyz")
        - traefik.http.routers.spcn19apache-https.tls.certresolver=default
        - traefik.http.services.spcn19apache.loadbalancer.server.port=80
      resources:
        reservations:
          cpus: '0.1'
          memory: 10M
        limits:
          cpus: '0.4'
          memory: 50M
networks:
  webproxy:
    external: true
volumes:
  app:
    external: false