version: '3.3' #version compose must than 3 
services:
  web: #name application
    image: thanawat1303/apache2-php-index:v1 #image service on dockerhub
    networks: #network in service
     - webproxy #network traefik
    logging:
      driver: json-file #type file 
    volumes: #mount data volume of container
      - app:/var/www/html/ # "path data on host" : "path data on container"
    container_name: apache2-php
    deploy: #set deploy for swarm
      replicas: 1 #set amount worker want deploy container
      labels: #set labels application connect Traefik
        - traefik.docker.network=webproxy #name network of Traefik
        - traefik.enable=true #status of connect
        - traefik.http.routers.spcn19apache-https.entrypoints=websecure #set position when have request to traefik
        - traefik.http.routers.spcn19apache-https.rule=Host("spcn19apache.xops.ipv9.xyz") #set domain access to application
        - traefik.http.routers.spcn19apache-https.tls.certresolver=default #set certresolver
        - traefik.http.services.spcn19apache.loadbalancer.server.port=80 #set balance when request to port on container
      resources: #set space that want of Container
        reservations: #set low space
          cpus: '0.1'
          memory: 10M
        limits: #set high space
          cpus: '0.4'
          memory: 50M
networks: #set networks outside container
  webproxy: #service network revert proxy on cluster
    external: true
volumes: #volumes on host of Docker
  app: