version: '3.3'
services:
  server:
    image: thanawat1303/apache2-php-index:latest
    networks:
     - webproxy
    logging:
      driver: json-file
    volumes:
      - app:/var/www/html/
    container_name: apache2-php
    deploy:
      replicas: 1
      labels:
        - traefik.docker.network=webproxy
        - traefik.enable=true
        - traefik.http.routers.spcn19apache-https.entrypoints=websecure
        - traefik.http.routers.spcn19apache-https.rule=Host("spcn19apache.xops.ipv9.xyz")
        - traefik.http.routers.spcn19apache-https.tls.certresolver=default
        - traefik.http.services.spcn19apache.loadbalancer.server.port=80
      resources:
        reservations:
          cpus: '0.1'
          memory: 10M
        limits:
          cpus: '0.4'
          memory: 50M
networks:
  webproxy:
    external: true
volumes:
  app:
    external: false